name: Tests

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run tests with Python 3.6
        run: |
          pip install "ansible-core<2.17"
          ansible-galaxy collection install . --collections-path .
          cd ./ansible_collections/neteye/upgrade_manager/
          ansible-test units --python 3.6 --docker
